# Generated by Django 3.2 on 2021-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_profile',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
